prefix = get_option('prefix')

extensions_dir = join_paths(prefix, 'share', 'gnome-shell', 'extensions', 'desktop-icons-ng@icookie-tea.github.io', 'app')

install_data([
    'ask-rename-popup.js',
    'auto-ar.js',
    'constants.js',
    'create-thumbnail.js',
    'dbus-interfaces.js',
    'dbus-utils.js',
    'dbus-remote-operations.js',
    'desktop-grid.js',
    'desktop-icon-item.js',
    'desktop-icons-util.js',
    'desktop-manager.js',
    'desktop-menu.js',
    'desktop-monitor.js',
    'ding.js',
    'grid-layout.js',
    'paint-container.js',
    'dnd-clipboard-utils.js',
    'dnd-manager.js',
    'enums.js',
    'file-changes-queue.js',
    'file-item.js',
    'file-operations.js',
    'file-item-menu.js',
    'file-utils.js',
    'keyboard-manager.js',
    'log.js',
    'menu-helper.js',
    'mount-manager.js',
    'preferences.js',
    'prefs-window.js',
    'promise-utils.js',
    'show-error-popup.js',
    'search-dialog.js',
    'selection-manager.js',
    'signals.js',
    'signal-manager.js',
    'sort-manager.js',
    'theme-manager.js',
    'stylesheet.css',
    'templates-scripts-manager.js',
    'thumbnails.js',
  ],
  install_dir: extensions_dir
)
